### ISSUE TITLE
The Legendary Coal Incident

### ISSUE THREAD

**Issue by Nathaniel2011** [McSnurtle/Project-Skyfall#132] opened 2024-11-20 00:46 UTC
**When was the crash**
I put 7 raw mutton into a furnace, then left the furnace got 1 piece of coal from a double chest, and then shift-clicked the coal in and immediately crashed

**Crash Log**

[The-Legendary-Coal-Incident.txt](https://github.com/user-attachments/files/17823077/The-Legendary-Coal-Incident.txt)

```
Replace this text with the contents of the relevant crash report
found in /.minecraft/crash-reports/crash-year-month-day_forgeversion-fml.txt
```

**Server Version**
v1.1.1

**Screenshots (Optional)**

**Additional Context (Optional)**
Any additional context to describe the crash.

**Comment by Nathaniel2011** [comment] 2024-11-20 00:47
"am i this dogwater?" - Bozo 2024 (also known as Joe Biden)

**Comment by McSnurtle** [comment] 2024-11-20 05:10
Dual 16GB DDR4, an i5 12600K, but a GTX 1070? Interesting... Vert interesting indeed...

**Comment by McSnurtle** [comment] 2024-11-20 05:15
No Shaders? [!Image](<https://www.google.com/imgres?q=Megamind%20no%20updates&imgurl=https%3A%2F%2Fpreview.redd.it%2Fno-updates-v0-d0s40vpwgro81.jpg%3Fwidth%3D1080%26crop%3Dsmart%26auto%3Dwebp%26s%3D074716ca383e0bf316d6854ee4420be22b7d6458&imgrefurl=https%3A%2F%2Fwww.reddit.com%2Fr%2Ftf2%2Fcomments%2Ftjfcq2%2Fno_updates%2F&docid=e67QDlAqALX6PM&tbnid=_FQ6lYbePOF9_M&vet=12ahUKEwi-lYHXk-qJAxVSFlkFHfa5JdQQM3oECHEQAA..i&w=1080&h=956&hcb=2&ved=2ahUKEwi-lYHXk-qJAxVSFlkFHfa5JdQQM3oECHEQAA>)

**Comment by McSnurtle** [comment] 2024-11-20 05:18
In all seriousness though, it seems this is caused by the smooth swapping mod. This is not a mandatory mod, but the problem should be solved by disabling it in it's config. I would strongly advise reposting this issue (or similar) to SmoothSwapping's github repo, as I cannot find any conflicts. Since this is a one off occurrence, I will close this now. Feel free to re-open / dupe if the issue persists.

**Closed by McSnurtle** 2024-11-20 05:18 UTC
Labels: bug, crashreport
